# Generated by Django 4.1.1 on 2022-10-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0003_task_pick_a_int"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="pick_a_int",
        ),
    ]
